// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Posonl.Web.Models;

public partial class PosCompanyRating
{
    public long Id { get; set; }

    public long PosCompanyId { get; set; }

    public long RatingCategoryId { get; set; }

    public decimal Score { get; set; }
}