//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posonl.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Posonl.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing &amp; Accounting .
        /// </summary>
        internal static string Category_BillingAndAccounting {
            get {
                return ResourceManager.GetString("Category.BillingAndAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer &amp; Loyalty Programs .
        /// </summary>
        internal static string Category_CustomerAndLoyaltyPrograms {
            get {
                return ResourceManager.GetString("Category.CustomerAndLoyaltyPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-commerce &amp; Online Payments .
        /// </summary>
        internal static string Category_EcommerceAndOnlinePayments {
            get {
                return ResourceManager.GetString("Category.EcommerceAndOnlinePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Solutions .
        /// </summary>
        internal static string Category_HardwareSolutions {
            get {
                return ResourceManager.GetString("Category.HardwareSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-currency &amp; Cross-border Payments .
        /// </summary>
        internal static string Category_MultiCurrencyAndCrossBorderPayments {
            get {
                return ResourceManager.GetString("Category.MultiCurrencyAndCrossBorderPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods .
        /// </summary>
        internal static string Category_PaymentMethods {
            get {
                return ResourceManager.GetString("Category.PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional-Specific POS Services .
        /// </summary>
        internal static string Category_RegionalSpecificPOSServices {
            get {
                return ResourceManager.GetString("Category.RegionalSpecificPOSServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting &amp; Analytics .
        /// </summary>
        internal static string Category_ReportingAndAnalytics {
            get {
                return ResourceManager.GetString("Category.ReportingAndAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security &amp; Fraud Prevention .
        /// </summary>
        internal static string Category_SecurityAndFraudPrevention {
            get {
                return ResourceManager.GetString("Category.SecurityAndFraudPrevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription &amp; Recurring Payments .
        /// </summary>
        internal static string Category_SubscriptionAndRecurringPayments {
            get {
                return ResourceManager.GetString("Category.SubscriptionAndRecurringPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Now.
        /// </summary>
        internal static string CompareNow {
            get {
                return ResourceManager.GetString("CompareNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Now.
        /// </summary>
        internal static string Hero_Button {
            get {
                return ResourceManager.GetString("Hero.Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare POS providers, find the lowest commission rates, and choose the best payment system for your business..
        /// </summary>
        internal static string Hero_Description {
            get {
                return ResourceManager.GetString("Hero.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the Best POS Solutions!.
        /// </summary>
        internal static string Hero_Title {
            get {
                return ResourceManager.GetString("Hero.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu.Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosCompanies.
        /// </summary>
        internal static string Menu_PosCompanies {
            get {
                return ResourceManager.GetString("Menu.PosCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Transaction Monitoring.
        /// </summary>
        internal static string PosService_AITransactionMonitoring {
            get {
                return ResourceManager.GetString("PosService.AITransactionMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_AITransactionMonitoringDescription {
            get {
                return ResourceManager.GetString("PosService.AITransactionMonitoringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AliPay China .
        /// </summary>
        internal static string PosService_AliPayChina {
            get {
                return ResourceManager.GetString("PosService.AliPayChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_AliPayChinaDescription {
            get {
                return ResourceManager.GetString("PosService.AliPayChinaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_AutomatedInvoicing {
            get {
                return ResourceManager.GetString("PosService.AutomatedInvoicing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_AutomatedInvoicingDescription {
            get {
                return ResourceManager.GetString("PosService.AutomatedInvoicingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_AutomatedSubscriptionBilling {
            get {
                return ResourceManager.GetString("PosService.AutomatedSubscriptionBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_AutomatedSubscriptionBillingDescription {
            get {
                return ResourceManager.GetString("PosService.AutomatedSubscriptionBillingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_BKMExpressPayment {
            get {
                return ResourceManager.GetString("PosService.BKMExpressPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_BKMExpressPaymentDescription {
            get {
                return ResourceManager.GetString("PosService.BKMExpressPaymentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_BuyNowPayLater {
            get {
                return ResourceManager.GetString("PosService.BuyNowPayLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_BuyNowPayLaterDescription {
            get {
                return ResourceManager.GetString("PosService.BuyNowPayLaterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CashbackOffers {
            get {
                return ResourceManager.GetString("PosService.CashbackOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CashbackOffersDescription {
            get {
                return ResourceManager.GetString("PosService.CashbackOffersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_ChargebackProtection {
            get {
                return ResourceManager.GetString("PosService.ChargebackProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_ChargebackProtectionDescription {
            get {
                return ResourceManager.GetString("PosService.ChargebackProtectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_ChaseMerchantServices {
            get {
                return ResourceManager.GetString("PosService.ChaseMerchantServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_ChaseMerchantServicesDescription {
            get {
                return ResourceManager.GetString("PosService.ChaseMerchantServicesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CheckoutOptimizations {
            get {
                return ResourceManager.GetString("PosService.CheckoutOptimizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CheckoutOptimizationsDescription {
            get {
                return ResourceManager.GetString("PosService.CheckoutOptimizationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_ContactlessPayments {
            get {
                return ResourceManager.GetString("PosService.ContactlessPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_ContactlessPaymentsDescription {
            get {
                return ResourceManager.GetString("PosService.ContactlessPaymentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CreditCardProcessing {
            get {
                return ResourceManager.GetString("PosService.CreditCardProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CrossBorderTransactionSecurity {
            get {
                return ResourceManager.GetString("PosService.CrossBorderTransactionSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CrossBorderTransactionSecurityDescription {
            get {
                return ResourceManager.GetString("PosService.CrossBorderTransactionSecurityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CryptoPayments {
            get {
                return ResourceManager.GetString("PosService.CryptoPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CryptoPaymentsDescription {
            get {
                return ResourceManager.GetString("PosService.CryptoPaymentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CustomerBehaviorReports {
            get {
                return ResourceManager.GetString("PosService.CustomerBehaviorReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CustomerBehaviorReportsDescription {
            get {
                return ResourceManager.GetString("PosService.CustomerBehaviorReportsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CustomerDataAnalytics {
            get {
                return ResourceManager.GetString("PosService.CustomerDataAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_CustomerDataAnalyticsDescription {
            get {
                return ResourceManager.GetString("PosService.CustomerDataAnalyticsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_DeferredPaymentProcessing {
            get {
                return ResourceManager.GetString("PosService.DeferredPaymentProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_DeferredPaymentProcessingDescription {
            get {
                return ResourceManager.GetString("PosService.DeferredPaymentProcessingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_DeviceFingerprinting {
            get {
                return ResourceManager.GetString("PosService.DeviceFingerprinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_DeviceFingerprintingDescription {
            get {
                return ResourceManager.GetString("PosService.DeviceFingerprintingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_DunningManagement {
            get {
                return ResourceManager.GetString("PosService.DunningManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_DunningManagementDescription {
            get {
                return ResourceManager.GetString("PosService.DunningManagementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_DynamicCurrencyConversion {
            get {
                return ResourceManager.GetString("PosService.DynamicCurrencyConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_DynamicCurrencyConversionDescription {
            get {
                return ResourceManager.GetString("PosService.DynamicCurrencyConversionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_EMVChipPayments {
            get {
                return ResourceManager.GetString("PosService.EMVChipPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_EMVChipPaymentsDescription {
            get {
                return ResourceManager.GetString("PosService.EMVChipPaymentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_EReceiptGeneration {
            get {
                return ResourceManager.GetString("PosService.EReceiptGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_EReceiptGenerationDescription {
            get {
                return ResourceManager.GetString("PosService.EReceiptGenerationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_ForexRateLocking {
            get {
                return ResourceManager.GetString("PosService.ForexRateLocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_ForexRateLockingDescription {
            get {
                return ResourceManager.GetString("PosService.ForexRateLockingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_GiftCardManagement {
            get {
                return ResourceManager.GetString("PosService.GiftCardManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_GiftCardManagementDescription {
            get {
                return ResourceManager.GetString("PosService.GiftCardManagementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_HandheldPOS {
            get {
                return ResourceManager.GetString("PosService.HandheldPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_HandheldPOSDescription {
            get {
                return ResourceManager.GetString("PosService.HandheldPOSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_iDealNetherlands {
            get {
                return ResourceManager.GetString("PosService.iDealNetherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_iDealNetherlandsDescription {
            get {
                return ResourceManager.GetString("PosService.iDealNetherlandsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_InternationalWireTransfers {
            get {
                return ResourceManager.GetString("PosService.InternationalWireTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_InternationalWireTransfersDescription {
            get {
                return ResourceManager.GetString("PosService.InternationalWireTransfersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_InventoryTracking {
            get {
                return ResourceManager.GetString("PosService.InventoryTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_InventoryTrackingDescription {
            get {
                return ResourceManager.GetString("PosService.InventoryTrackingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_LoyaltyRewards {
            get {
                return ResourceManager.GetString("PosService.LoyaltyRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_LoyaltyRewardsDescription {
            get {
                return ResourceManager.GetString("PosService.LoyaltyRewardsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_MerchantVirtualTerminals {
            get {
                return ResourceManager.GetString("PosService.MerchantVirtualTerminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_MerchantVirtualTerminalsDescription {
            get {
                return ResourceManager.GetString("PosService.MerchantVirtualTerminalsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_MobilePayments {
            get {
                return ResourceManager.GetString("PosService.MobilePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_MobilePaymentsDescription {
            get {
                return ResourceManager.GetString("PosService.MobilePaymentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_MultiCurrencyBilling {
            get {
                return ResourceManager.GetString("PosService.MultiCurrencyBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_MultiCurrencyBillingDescription {
            get {
                return ResourceManager.GetString("PosService.MultiCurrencyBillingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_MultiCurrencyPOSBilling {
            get {
                return ResourceManager.GetString("PosService.MultiCurrencyPOSBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_MultiCurrencyPOSBillingDescription {
            get {
                return ResourceManager.GetString("PosService.MultiCurrencyPOSBillingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_PaymentLinks {
            get {
                return ResourceManager.GetString("PosService.PaymentLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_PaymentLinksDescription {
            get {
                return ResourceManager.GetString("PosService.PaymentLinksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_PayNowSingapore {
            get {
                return ResourceManager.GetString("PosService.PayNowSingapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_PayNowSingaporeDescription {
            get {
                return ResourceManager.GetString("PosService.PayNowSingaporeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_PointRedemption {
            get {
                return ResourceManager.GetString("PosService.PointRedemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_PointRedemptionDescription {
            get {
                return ResourceManager.GetString("PosService.PointRedemptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_POSAccountingIntegration {
            get {
                return ResourceManager.GetString("PosService.POSAccountingIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_POSAccountingIntegrationDescription {
            get {
                return ResourceManager.GetString("PosService.POSAccountingIntegrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_POSDeviceHealthMonitoring {
            get {
                return ResourceManager.GetString("PosService.POSDeviceHealthMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_POSDeviceHealthMonitoringDescription {
            get {
                return ResourceManager.GetString("PosService.POSDeviceHealthMonitoringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_RecurringPaymentManagement {
            get {
                return ResourceManager.GetString("PosService.RecurringPaymentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_RecurringPaymentManagementDescription {
            get {
                return ResourceManager.GetString("PosService.RecurringPaymentManagementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_RevenueForecastingDescription {
            get {
                return ResourceManager.GetString("PosService.RevenueForecastingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_RiskScoring {
            get {
                return ResourceManager.GetString("PosService.RiskScoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_RiskScoringDescription {
            get {
                return ResourceManager.GetString("PosService.RiskScoringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_SalesAnalytics {
            get {
                return ResourceManager.GetString("PosService.SalesAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_SalesAnalyticsDescription {
            get {
                return ResourceManager.GetString("PosService.SalesAnalyticsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_SelfCheckoutKiosks {
            get {
                return ResourceManager.GetString("PosService.SelfCheckoutKiosks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_SelfCheckoutKiosksDescription {
            get {
                return ResourceManager.GetString("PosService.SelfCheckoutKiosksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_SplitPayments {
            get {
                return ResourceManager.GetString("PosService.SplitPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_SplitPaymentsDescription {
            get {
                return ResourceManager.GetString("PosService.SplitPaymentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_SquarePOS {
            get {
                return ResourceManager.GetString("PosService.SquarePOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_SquarePOSDescription {
            get {
                return ResourceManager.GetString("PosService.SquarePOSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_SubscriptionBilling {
            get {
                return ResourceManager.GetString("PosService.SubscriptionBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_SubscriptionBillingDescription {
            get {
                return ResourceManager.GetString("PosService.SubscriptionBillingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_TabletPOS {
            get {
                return ResourceManager.GetString("PosService.TabletPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_TabletPOSDescription {
            get {
                return ResourceManager.GetString("PosService.TabletPOSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_TaxIntegration {
            get {
                return ResourceManager.GetString("PosService.TaxIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_TaxIntegrationDescription {
            get {
                return ResourceManager.GetString("PosService.TaxIntegrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_ToastPOS {
            get {
                return ResourceManager.GetString("PosService.ToastPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_ToastPOSDescription {
            get {
                return ResourceManager.GetString("PosService.ToastPOSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_TraditionalPOSMachines {
            get {
                return ResourceManager.GetString("PosService.TraditionalPOSMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_TraditionalPOSMachinesDescription {
            get {
                return ResourceManager.GetString("PosService.TraditionalPOSMachinesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("PosService.TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_TwoFactorAuthenticationDescription {
            get {
                return ResourceManager.GetString("PosService.TwoFactorAuthenticationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_UPIPaymentsIndia {
            get {
                return ResourceManager.GetString("PosService.UPIPaymentsIndia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_UPIPaymentsIndiaDescription {
            get {
                return ResourceManager.GetString("PosService.UPIPaymentsIndiaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_UsageBasedBilling {
            get {
                return ResourceManager.GetString("PosService.UsageBasedBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_UsageBasedBillingDescription {
            get {
                return ResourceManager.GetString("PosService.UsageBasedBillingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_WeChatPayChina {
            get {
                return ResourceManager.GetString("PosService.WeChatPayChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_WeChatPayChinaDescription {
            get {
                return ResourceManager.GetString("PosService.WeChatPayChinaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_WirelessPOS {
            get {
                return ResourceManager.GetString("PosService.WirelessPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PosService_WirelessPOSDescription {
            get {
                return ResourceManager.GetString("PosService.WirelessPOSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
    }
}
