name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main  # Ana dalın adı (değiştirilebilir)
    paths:
      - '**/*.csproj'  # Sadece csproj dosyasındaki değişikliklerde tetiklesin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Kullanmak istediğiniz .NET sürümünü yazın

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Pack the NuGet package
      run: dotnet pack --configuration Release --no-build --output ./nupkgs

    - name: Publish NuGet package to GitHub Packages
      run: dotnet nuget push ./nupkgs/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
