name: Build and Publish NuGet Package

on:
  push:
    branches:
      - '*'  # Tüm dallarda tetiklenecek şekilde ayarlandı
    paths:
      - '**/*'  # Tüm dosya değişikliklerinde tetiklensin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      # .NET 8.0 SDK'sını kuruyoruz
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Projeniz .NET 8.0 kullanıyorsa

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Pack the NuGet package
      run: dotnet pack --configuration Release --no-build --output ./nupkgs

    - name: Publish NuGet package to GitHub Packages
      run: dotnet nuget push ./nupkgs/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
